services:
  - type: web
    name: rydex-socket-server
    env: node
    region: oregon
    rootDir: socketServer
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
